huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
huggingface-cli download  --repo-type dataset --resume-download poloclub/diffusiondb --local-dir "/data/Hszhu/dataset/diffusiondb" --local-dir-use-symlinks False --resume-download
